address: 0.0.0.0:10081
transport: tcp
protocol:
  type: ws
  targets:
    - matching_path: /4BF20093
      protocol:
        type: vmess
        cipher: any
        user_id: 4BF20093-7DD8-4EE4-A681-B6DDACAC0D60
rules:
  - mask: 0.0.0.0/0
    action: allow
    client_proxy: direct
